import tkinter as tk
root = tk.Tk()
root.title("Sudoku Game")
root.geometry("400x300")
root.configure(bg="#f0f8ff")
# window = tk.Tk()
# window.title("Sudoku Game")
# # window.resizable(False, False)
# canvas = tk.Canvas(window, width=500, height=600)
# canvas.grid(sticky='nsew')